// Code generated by bazel/pbgen. DO NOT EDIT.
// clang-format off

#pragma once

#include "bytes/iobuf.h"
#include "container/chunked_hash_map.h"
#include "container/chunked_vector.h"
#include "absl/time/time.h"
#include "serde/protobuf/field_mask.h"

#include <seastar/core/future.hh>
#include <seastar/core/sstring.hh>

class iobuf_parser;

namespace serde::pb {
class wire_format_parser;
}
namespace serde::pb::json {
class peekable_parser;
}

namespace proto::example {

class a;
class b;
class c;
class well_known_protos;

// Test that enums that have prefixes in their values as recommended by protobuf
// are stripped and turned into enum classes.
// 
// See: https://protobuf.dev/programming-guides/proto3/#enum
enum class corpus : uint8_t {
  unspecified = 0,
  universal = 1,
  web = 2,
  images = 3,
  local = 4,
  news = 5,
  products = 6,
  video = 7,
};
void enum_to_proto(const corpus&, iobuf*);
void enum_from_proto(iobuf_parser*, corpus*);
// Returns the name of the enum value
std::string_view enum_to_string(const corpus&);
void enum_from_json(serde::pb::json::peekable_parser*, corpus*);

enum class protobuf3_test : uint8_t {
  unspecified = 0,
  started = 1,
  running = 1,
  finished = 2,
};
void enum_to_proto(const protobuf3_test&, iobuf*);
void enum_from_proto(iobuf_parser*, protobuf3_test*);
// Returns the name of the enum value
std::string_view enum_to_string(const protobuf3_test&);
void enum_from_json(serde::pb::json::peekable_parser*, protobuf3_test*);

enum class proto3_test : uint8_t {
  unspecified = 0,
  started = 1,
  finished = 2,
};
void enum_to_proto(const proto3_test&, iobuf*);
void enum_from_proto(iobuf_parser*, proto3_test*);
// Returns the name of the enum value
std::string_view enum_to_string(const proto3_test&);
void enum_from_json(serde::pb::json::peekable_parser*, proto3_test*);

class c {
public:
  c() noexcept;
  c(const c&) = delete;
  c& operator=(const c&) = delete;
  c(c&&) noexcept;
  c& operator=(c&&) noexcept;
  ~c() noexcept;
  
  bool operator==(const c&) const;  
  // Serializes example.C into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.C into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.C from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<c> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, c*);
  // Deserializes example.C from json, in a way that will not cause stalls for large messages.
  static seastar::future<c> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, c*);
  

private:
};

class a {
public:
  a() noexcept;
  a(const a&) = delete;
  a& operator=(const a&) = delete;
  a(a&&) noexcept;
  a& operator=(a&&) noexcept;
  ~a() noexcept;
  
  bool operator==(const a&) const;  
  // Serializes example.A into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.A into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.A from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<a> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, a*);
  // Deserializes example.A from json, in a way that will not cause stalls for large messages.
  static seastar::future<a> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, a*);
  
  c& get_c();
  const c& get_c() const;
  void set_c(c&& v);

private:
  c c_;
};

class b {
public:
  b() noexcept;
  b(const b&) = delete;
  b& operator=(const b&) = delete;
  b(b&&) noexcept;
  b& operator=(b&&) noexcept;
  ~b() noexcept;
  
  bool operator==(const b&) const;  
  // Serializes example.B into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.B into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.B from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<b> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, b*);
  // Deserializes example.B from json, in a way that will not cause stalls for large messages.
  static seastar::future<b> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, b*);
  
  c& get_c();
  const c& get_c() const;
  void set_c(c&& v);
  a& get_a();
  const a& get_a() const;
  void set_a(a&& v);

private:
  c c_;
  a a_;
};

class well_known_protos {
public:
  well_known_protos() noexcept;
  well_known_protos(const well_known_protos&) = delete;
  well_known_protos& operator=(const well_known_protos&) = delete;
  well_known_protos(well_known_protos&&) noexcept;
  well_known_protos& operator=(well_known_protos&&) noexcept;
  ~well_known_protos() noexcept;
  
  bool operator==(const well_known_protos&) const;  
  // Serializes example.WellKnownProtos into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.WellKnownProtos into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.WellKnownProtos from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<well_known_protos> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, well_known_protos*);
  // Deserializes example.WellKnownProtos from json, in a way that will not cause stalls for large messages.
  static seastar::future<well_known_protos> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, well_known_protos*);
  
  absl::Duration& get_single_duration();
  const absl::Duration& get_single_duration() const;
  void set_single_duration(absl::Duration&& v);
  chunked_vector<absl::Duration>& get_repeated_duration();
  const chunked_vector<absl::Duration>& get_repeated_duration() const;
  void set_repeated_duration(chunked_vector<absl::Duration>&& v);
  chunked_hash_map<ss::sstring, absl::Duration>& get_duration_map();
  const chunked_hash_map<ss::sstring, absl::Duration>& get_duration_map() const;
  void set_duration_map(chunked_hash_map<ss::sstring, absl::Duration>&& v);
  serde::pb::field_mask& get_single_field_mask();
  const serde::pb::field_mask& get_single_field_mask() const;
  void set_single_field_mask(serde::pb::field_mask&& v);
  chunked_vector<serde::pb::field_mask>& get_repeated_field_mask();
  const chunked_vector<serde::pb::field_mask>& get_repeated_field_mask() const;
  void set_repeated_field_mask(chunked_vector<serde::pb::field_mask>&& v);
  chunked_hash_map<ss::sstring, serde::pb::field_mask>& get_field_mask_map();
  const chunked_hash_map<ss::sstring, serde::pb::field_mask>& get_field_mask_map() const;
  void set_field_mask_map(chunked_hash_map<ss::sstring, serde::pb::field_mask>&& v);

private:
  absl::Duration single_duration_;
  chunked_vector<absl::Duration> repeated_duration_;
  chunked_hash_map<ss::sstring, absl::Duration> duration_map_;
  serde::pb::field_mask single_field_mask_;
  chunked_vector<serde::pb::field_mask> repeated_field_mask_;
  chunked_hash_map<ss::sstring, serde::pb::field_mask> field_mask_map_;
};

} // proto::example
