from _typeshed import Incomplete
from ducktape.errors import DucktapeError as DucktapeError
from typing import Callable, TypeVar

from rptest.services.cluster import Any

_F = TypeVar("_F", bound=Callable[..., object])

class Mark:
    @staticmethod
    def mark(fun, mark) -> None: ...
    @staticmethod
    def marked(f, mark): ...
    @staticmethod
    def clear_marks(f) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list) -> None: ...
    def __eq__(self, other): ...

class Ignore(Mark):
    injected_args: Incomplete
    def __init__(self, **kwargs) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list): ...
    def __eq__(self, other): ...

class IgnoreAll(Ignore):
    injected_args: Incomplete
    def __init__(self) -> None: ...

class OkToFail(Mark):
    injected_args: Incomplete
    def __init__(self) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list): ...

class Matrix(Mark):
    injected_args: Incomplete
    def __init__(self, **kwargs) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list): ...
    def __eq__(self, other): ...

class Defaults(Mark):
    injected_args: Incomplete
    def __init__(self, **kwargs) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list): ...
    def __eq__(self, other): ...

class Parametrize(Mark):
    injected_args: Incomplete
    def __init__(self, **kwargs) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list): ...
    def __eq__(self, other): ...

class Env(Mark):
    injected_args: Incomplete
    should_ignore: Incomplete
    def __init__(self, **kwargs) -> None: ...
    @property
    def name(self): ...
    def apply(self, seed_context, context_list): ...
    def __eq__(self, other): ...

PARAMETRIZED: Incomplete
MATRIX: Incomplete
DEFAULTS: Incomplete
IGNORE: Incomplete
OK_TO_FAIL: Incomplete
ENV: Incomplete

def parametrized(f): ...
def ignored(f): ...
def oked_to_fail(f): ...
def is_env(f): ...
def cartesian_product_dict(d): ...
def matrix(**kwargs: Any) -> Callable[[_F], _F]: ...
def defaults(**kwargs): ...
def parametrize(**kwargs): ...
def ignore(*args, **kwargs): ...
def ok_to_fail(*args, **kwargs): ...
def env(**kwargs): ...
