#!/usr/bin/env bash
set -e
mkdir -p /opt/scripts
curl https://raw.githubusercontent.com/scylladb/seastar/0af88fa21226394ecbfe109b428774f96b73dcb2/scripts/addr2line.py -o /opt/scripts/addr2line.py
curl https://raw.githubusercontent.com/scylladb/seastar/0af88fa21226394ecbfe109b428774f96b73dcb2/scripts/seastar-addr2line -o /opt/scripts/seastar-addr2line
chmod +x /opt/scripts/seastar-addr2line
