#!/usr/bin/env bash
set -e
mkdir /opt/librdkafka
curl -SL "https://vectorized-public.s3.us-west-2.amazonaws.com/dependencies/librdkafka-v2.12.1.tar.gz" | tar -xz --strip-components=1 -C /opt/librdkafka
cd /opt/librdkafka
./configure --enable-gssapi --enable-curl
make -j$(nproc)
make install
cd /opt/librdkafka/tests
make build -j$(nproc)
