#!/usr/bin/env bash

# "tool packages" are generally those which are needed for running ducktape
# tests, but not for building the early layers of the image themselves. They
# are installed relatively late in the Dockerfile, after most of the heavy
# "non mainline" layers have forked off.
set -e
apt-get update
apt-get install -qq \
  bind9-dnsutils \
  bind9-utils \
  bsdmainutils \
  dmidecode \
  faketime \
  file \
  gnuplot-nox \
  iproute2 \
  iptables \
  krb5-admin-server \
  krb5-kdc \
  krb5-user \
  libatomic1 \
  libyajl-dev \
  llvm \
  lsof \
  net-tools \
  netcat-openbsd \
  nodejs \
  npm \
  openssh-server \
  pciutils \
  sudo
