#!/usr/bin/env bash

# "tool packages" are generally those which are needed for running ducktape
# tests, but not for building the early layers of the image themselves. They
# are installed relatively late in the Dockerfile, after most of the heavy
# "non mainline" layers have forked off.
set -e
apt-get update
apt-get install -qq \
  bind9-dnsutils \
  bind9-utils \
  bsdmainutils \
  dmidecode \
  faketime \
  file \
  gnuplot-nox \
  iproute2 \
  iptables \
  krb5-admin-server \
  krb5-kdc \
  krb5-user \
  libatomic1 \
  libyajl-dev \
  lsof \
  net-tools \
  netcat-openbsd \
  nodejs \
  npm \
  openssh-server \
  pciutils \
  software-properties-common \
  sudo

# install llvm-addr2line-$(version), which is not available in the default ubuntu/debian repos,
# but is needed to demangle seastar backtraces (much faster than binutils addr2line)

LLVM_VERSION=20

cd "$(mktemp -d)"
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh $LLVM_VERSION
mkdir -p /opt/llvm
# make it available in a version-independent way
ln -s /usr/bin/llvm-addr2line-$LLVM_VERSION /opt/llvm/llvm-addr2line
