{
 "title": "Cloud Topics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Write Request Scheduler",
   "type": "timeseries",
   "description": "Throughput of data per scheduler decision of either time or size based threshold.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_cloud_topics_write_request_scheduler_time_fallback_bytes[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(vectorized_cloud_topics_write_request_scheduler_data_threshold_bytes[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader_router: Add Objects (p50)",
   "type": "timeseries",
   "description": "Latency of local add_objects requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_add_objects_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Add Objects (p99)",
   "type": "timeseries",
   "description": "Latency of local add_objects requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_add_objects_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Replace Objects (p50)",
   "type": "timeseries",
   "description": "Latency of local replace_objects requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_replace_objects_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Replace Objects (p99)",
   "type": "timeseries",
   "description": "Latency of local replace_objects requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_replace_objects_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get First Offset GE (p50)",
   "type": "timeseries",
   "description": "Latency of local get_first_offset_ge requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_first_offset_ge_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get First Offset GE (p99)",
   "type": "timeseries",
   "description": "Latency of local get_first_offset_ge requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_first_offset_ge_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get First Timestamp GE (p50)",
   "type": "timeseries",
   "description": "Latency of local get_first_timestamp_ge requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_first_timestamp_ge_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get First Timestamp GE (p99)",
   "type": "timeseries",
   "description": "Latency of local get_first_timestamp_ge requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_first_timestamp_ge_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get First Offset For Bytes (p50)",
   "type": "timeseries",
   "description": "Latency of local get_first_offset_for_bytes requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_first_offset_for_bytes_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get First Offset For Bytes (p99)",
   "type": "timeseries",
   "description": "Latency of local get_first_offset_for_bytes requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_first_offset_for_bytes_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Offsets (p50)",
   "type": "timeseries",
   "description": "Latency of local get_offsets requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_offsets_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Offsets (p99)",
   "type": "timeseries",
   "description": "Latency of local get_offsets requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_offsets_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Size (p50)",
   "type": "timeseries",
   "description": "Latency of local get_size requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_size_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Size (p99)",
   "type": "timeseries",
   "description": "Latency of local get_size requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_size_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Compaction Info (p50)",
   "type": "timeseries",
   "description": "Latency of local get_compaction_info requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_compaction_info_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Compaction Info (p99)",
   "type": "timeseries",
   "description": "Latency of local get_compaction_info requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_compaction_info_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Term For Offset (p50)",
   "type": "timeseries",
   "description": "Latency of local get_term_for_offset requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_term_for_offset_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Term For Offset (p99)",
   "type": "timeseries",
   "description": "Latency of local get_term_for_offset requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_term_for_offset_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get End Offset For Term (p50)",
   "type": "timeseries",
   "description": "Latency of local get_end_offset_for_term requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_end_offset_for_term_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get End Offset For Term (p99)",
   "type": "timeseries",
   "description": "Latency of local get_end_offset_for_term requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_end_offset_for_term_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Set Start Offset (p50)",
   "type": "timeseries",
   "description": "Latency of local set_start_offset requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_set_start_offset_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Set Start Offset (p99)",
   "type": "timeseries",
   "description": "Latency of local set_start_offset requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_set_start_offset_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Remove Topics (p50)",
   "type": "timeseries",
   "description": "Latency of local remove_topics requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_remove_topics_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Remove Topics (p99)",
   "type": "timeseries",
   "description": "Latency of local remove_topics requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_remove_topics_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Compaction Infos (p50)",
   "type": "timeseries",
   "description": "Latency of local get_compaction_infos requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_compaction_infos_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Compaction Infos (p99)",
   "type": "timeseries",
   "description": "Latency of local get_compaction_infos requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_compaction_infos_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Extent Metadata (p50)",
   "type": "timeseries",
   "description": "Latency of local get_extent_metadata requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_get_extent_metadata_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Get Extent Metadata (p99)",
   "type": "timeseries",
   "description": "Latency of local get_extent_metadata requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_get_extent_metadata_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Flush Domain (p50)",
   "type": "timeseries",
   "description": "Latency of local flush_domain requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_flush_domain_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Flush Domain (p99)",
   "type": "timeseries",
   "description": "Latency of local flush_domain requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_flush_domain_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Restore Domain (p50)",
   "type": "timeseries",
   "description": "Latency of local restore_domain requests (p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vectorized_cloud_topics_l1_leader_router_restore_domain_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_router: Restore Domain (p99)",
   "type": "timeseries",
   "description": "Latency of local restore_domain requests (p99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_cloud_topics_l1_leader_router_restore_domain_duration_microseconds_bucket[$__rate_interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}