"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LifecycleState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LifecycleStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LifecycleState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LIFECYCLE_STATE_UNSPECIFIED: _LifecycleState.ValueType
    LIFECYCLE_STATE_LIVE: _LifecycleState.ValueType
    LIFECYCLE_STATE_CLOSED: _LifecycleState.ValueType
    LIFECYCLE_STATE_PURGED: _LifecycleState.ValueType

class LifecycleState(_LifecycleState, metaclass=_LifecycleStateEnumTypeWrapper):
    ...
LIFECYCLE_STATE_UNSPECIFIED: LifecycleState.ValueType
LIFECYCLE_STATE_LIVE: LifecycleState.ValueType
LIFECYCLE_STATE_CLOSED: LifecycleState.ValueType
LIFECYCLE_STATE_PURGED: LifecycleState.ValueType
global___LifecycleState = LifecycleState

@typing.final
class GetCoordinatorStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOPICS_FILTER_FIELD_NUMBER: builtins.int

    @property
    def topics_filter(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of topics whose state to return. If empty, returns state for all
        topics.
        """

    def __init__(self, *, topics_filter: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['topics_filter', b'topics_filter']) -> None:
        ...
global___GetCoordinatorStateRequest = GetCoordinatorStateRequest

@typing.final
class GetCoordinatorStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int

    @property
    def state(self) -> global___CoordinatorState:
        ...

    def __init__(self, *, state: global___CoordinatorState | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['state', b'state']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['state', b'state']) -> None:
        ...
global___GetCoordinatorStateResponse = GetCoordinatorStateResponse

@typing.final
class CoordinatorState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TopicStatesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str

        @property
        def value(self) -> global___TopicState:
            ...

        def __init__(self, *, key: builtins.str=..., value: global___TopicState | None=...) -> None:
            ...

        def HasField(self, field_name: typing.Literal['value', b'value']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    TOPIC_STATES_FIELD_NUMBER: builtins.int

    @property
    def topic_states(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___TopicState]:
        ...

    def __init__(self, *, topic_states: collections.abc.Mapping[builtins.str, global___TopicState] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['topic_states', b'topic_states']) -> None:
        ...
global___CoordinatorState = CoordinatorState

@typing.final
class DataFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REMOTE_PATH_FIELD_NUMBER: builtins.int
    ROW_COUNT_FIELD_NUMBER: builtins.int
    FILE_SIZE_BYTES_FIELD_NUMBER: builtins.int
    TABLE_SCHEMA_ID_FIELD_NUMBER: builtins.int
    PARTITION_SPEC_ID_FIELD_NUMBER: builtins.int
    PARTITION_KEY_FIELD_NUMBER: builtins.int
    remote_path: builtins.str
    row_count: builtins.int
    file_size_bytes: builtins.int
    table_schema_id: builtins.int
    partition_spec_id: builtins.int

    @property
    def partition_key(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        ...

    def __init__(self, *, remote_path: builtins.str=..., row_count: builtins.int=..., file_size_bytes: builtins.int=..., table_schema_id: builtins.int=..., partition_spec_id: builtins.int=..., partition_key: collections.abc.Iterable[builtins.bytes] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['file_size_bytes', b'file_size_bytes', 'partition_key', b'partition_key', 'partition_spec_id', b'partition_spec_id', 'remote_path', b'remote_path', 'row_count', b'row_count', 'table_schema_id', b'table_schema_id']) -> None:
        ...
global___DataFile = DataFile

@typing.final
class TranslatedOffsetRange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_OFFSET_FIELD_NUMBER: builtins.int
    LAST_OFFSET_FIELD_NUMBER: builtins.int
    DATA_FILES_FIELD_NUMBER: builtins.int
    DLQ_FILES_FIELD_NUMBER: builtins.int
    KAFKA_PROCESSED_BYTES_FIELD_NUMBER: builtins.int
    start_offset: builtins.int
    last_offset: builtins.int
    kafka_processed_bytes: builtins.int

    @property
    def data_files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataFile]:
        ...

    @property
    def dlq_files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataFile]:
        ...

    def __init__(self, *, start_offset: builtins.int=..., last_offset: builtins.int=..., data_files: collections.abc.Iterable[global___DataFile] | None=..., dlq_files: collections.abc.Iterable[global___DataFile] | None=..., kafka_processed_bytes: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['data_files', b'data_files', 'dlq_files', b'dlq_files', 'kafka_processed_bytes', b'kafka_processed_bytes', 'last_offset', b'last_offset', 'start_offset', b'start_offset']) -> None:
        ...
global___TranslatedOffsetRange = TranslatedOffsetRange

@typing.final
class PendingEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    ADDED_PENDING_AT_FIELD_NUMBER: builtins.int
    added_pending_at: builtins.int

    @property
    def data(self) -> global___TranslatedOffsetRange:
        ...

    def __init__(self, *, data: global___TranslatedOffsetRange | None=..., added_pending_at: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['data', b'data']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['added_pending_at', b'added_pending_at', 'data', b'data']) -> None:
        ...
global___PendingEntry = PendingEntry

@typing.final
class PartitionState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PENDING_ENTRIES_FIELD_NUMBER: builtins.int
    LAST_COMMITTED_FIELD_NUMBER: builtins.int
    last_committed: builtins.int

    @property
    def pending_entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PendingEntry]:
        ...

    def __init__(self, *, pending_entries: collections.abc.Iterable[global___PendingEntry] | None=..., last_committed: builtins.int | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_last_committed', b'_last_committed', 'last_committed', b'last_committed']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_last_committed', b'_last_committed', 'last_committed', b'last_committed', 'pending_entries', b'pending_entries']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_last_committed', b'_last_committed']) -> typing.Literal['last_committed'] | None:
        ...
global___PartitionState = PartitionState

@typing.final
class TopicState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PartitionStatesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int

        @property
        def value(self) -> global___PartitionState:
            ...

        def __init__(self, *, key: builtins.int=..., value: global___PartitionState | None=...) -> None:
            ...

        def HasField(self, field_name: typing.Literal['value', b'value']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    REVISION_FIELD_NUMBER: builtins.int
    PARTITION_STATES_FIELD_NUMBER: builtins.int
    LIFECYCLE_STATE_FIELD_NUMBER: builtins.int
    TOTAL_KAFKA_PROCESSED_BYTES_FIELD_NUMBER: builtins.int
    revision: builtins.int
    lifecycle_state: global___LifecycleState.ValueType
    total_kafka_processed_bytes: builtins.int

    @property
    def partition_states(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___PartitionState]:
        ...

    def __init__(self, *, revision: builtins.int=..., partition_states: collections.abc.Mapping[builtins.int, global___PartitionState] | None=..., lifecycle_state: global___LifecycleState.ValueType=..., total_kafka_processed_bytes: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['lifecycle_state', b'lifecycle_state', 'partition_states', b'partition_states', 'revision', b'revision', 'total_kafka_processed_bytes', b'total_kafka_processed_bytes']) -> None:
        ...
global___TopicState = TopicState