[package]
name = "json2avro"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
redpanda-transform-sdk = { path = "../.." }
serde_json = "1.0.108"
apache-avro = "0.16.0"
anyhow = { workspace = true }
