"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from ........ import proto
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetOffsetsRequest(google.protobuf.message.Message):
    """GetOffsetsRequest is the request for looking up the offsets in the metastore
    for a topic partition.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int

    @property
    def partition(self) -> proto.redpanda.core.common.v1.ntp_pb2.TopicPartition:
        """The topic partition to lookup the offstes for."""

    def __init__(self, *, partition: proto.redpanda.core.common.v1.ntp_pb2.TopicPartition | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['partition', b'partition']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['partition', b'partition']) -> None:
        ...
Global___GetOffsetsRequest: typing_extensions.TypeAlias = GetOffsetsRequest

@typing.final
class GetOffsetsResponse(google.protobuf.message.Message):
    """GetOffsetsResponse is the response for looking up the offsets in the
    metastore.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OFFSETS_FIELD_NUMBER: builtins.int

    @property
    def offsets(self) -> Global___Offsets:
        """The offsets for this ntp in the metastore."""

    def __init__(self, *, offsets: Global___Offsets | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['offsets', b'offsets']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['offsets', b'offsets']) -> None:
        ...
Global___GetOffsetsResponse: typing_extensions.TypeAlias = GetOffsetsResponse

@typing.final
class Offsets(google.protobuf.message.Message):
    """The range of offsets stored in the metastore."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_OFFSET_FIELD_NUMBER: builtins.int
    NEXT_OFFSET_FIELD_NUMBER: builtins.int
    start_offset: builtins.int
    'The first offset available in the metastore.'
    next_offset: builtins.int
    'The next offset expected to be written to the metastore. It is\n    the exclusive upper bound of what is stored in the metastore.\n    '

    def __init__(self, *, start_offset: builtins.int=..., next_offset: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['next_offset', b'next_offset', 'start_offset', b'start_offset']) -> None:
        ...
Global___Offsets: typing_extensions.TypeAlias = Offsets

@typing.final
class GetSizeRequest(google.protobuf.message.Message):
    """GetSizeRequest is the request for looking up the size in bytes in the
    metastore for a topic partition.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int

    @property
    def partition(self) -> proto.redpanda.core.common.v1.ntp_pb2.TopicPartition:
        """The topic partition to lookup the size for."""

    def __init__(self, *, partition: proto.redpanda.core.common.v1.ntp_pb2.TopicPartition | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['partition', b'partition']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['partition', b'partition']) -> None:
        ...
Global___GetSizeRequest: typing_extensions.TypeAlias = GetSizeRequest

@typing.final
class GetSizeResponse(google.protobuf.message.Message):
    """GetSizeResponse is the response for looking up the size in the metastore."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    size_bytes: builtins.int
    'The size in bytes of this partition in the metastore.'

    def __init__(self, *, size_bytes: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['size_bytes', b'size_bytes']) -> None:
        ...
Global___GetSizeResponse: typing_extensions.TypeAlias = GetSizeResponse

@typing.final
class GetDatabaseStatsRequest(google.protobuf.message.Message):
    """GetDatabaseStatsRequest is the request for looking up LSM storage statistics."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    METASTORE_PARTITION_FIELD_NUMBER: builtins.int
    metastore_partition: builtins.int
    'The metastore partition to query. Defaults to partition 0 if not\n    specified.\n    '

    def __init__(self, *, metastore_partition: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['metastore_partition', b'metastore_partition']) -> None:
        ...
Global___GetDatabaseStatsRequest: typing_extensions.TypeAlias = GetDatabaseStatsRequest

@typing.final
class GetDatabaseStatsResponse(google.protobuf.message.Message):
    """GetDatabaseStatsResponse contains detailed LSM storage statistics."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACTIVE_MEMTABLE_BYTES_FIELD_NUMBER: builtins.int
    IMMUTABLE_MEMTABLE_BYTES_FIELD_NUMBER: builtins.int
    TOTAL_SIZE_BYTES_FIELD_NUMBER: builtins.int
    LEVELS_FIELD_NUMBER: builtins.int
    active_memtable_bytes: builtins.int
    'Size of the active memtable (data not yet flushed).'
    immutable_memtable_bytes: builtins.int
    'Size of the immutable memtable (data being flushed).'
    total_size_bytes: builtins.int
    'Total size including memtables and all levels.'

    @property
    def levels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___LsmLevel]:
        """Per-level file information for the LSM tree."""

    def __init__(self, *, active_memtable_bytes: builtins.int=..., immutable_memtable_bytes: builtins.int=..., total_size_bytes: builtins.int=..., levels: collections.abc.Iterable[Global___LsmLevel] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['active_memtable_bytes', b'active_memtable_bytes', 'immutable_memtable_bytes', b'immutable_memtable_bytes', 'levels', b'levels', 'total_size_bytes', b'total_size_bytes']) -> None:
        ...
Global___GetDatabaseStatsResponse: typing_extensions.TypeAlias = GetDatabaseStatsResponse

@typing.final
class LsmLevel(google.protobuf.message.Message):
    """Information about a single level in the LSM tree."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LEVEL_NUMBER_FIELD_NUMBER: builtins.int
    FILES_FIELD_NUMBER: builtins.int
    level_number: builtins.int
    'The level number (0 for L0, 1 for L1, etc).'

    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___LsmFile]:
        """Files in this level."""

    def __init__(self, *, level_number: builtins.int=..., files: collections.abc.Iterable[Global___LsmFile] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['files', b'files', 'level_number', b'level_number']) -> None:
        ...
Global___LsmLevel: typing_extensions.TypeAlias = LsmLevel

@typing.final
class LsmFile(google.protobuf.message.Message):
    """Summary information about a single SST file."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCH_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    SMALLEST_KEY_INFO_FIELD_NUMBER: builtins.int
    LARGEST_KEY_INFO_FIELD_NUMBER: builtins.int
    epoch: builtins.int
    'Database epoch when the file was created.'
    id: builtins.int
    'File ID.'
    size_bytes: builtins.int
    'File size in bytes.'
    smallest_key_info: builtins.str
    'Smallest key in the file (human-readable string representation).'
    largest_key_info: builtins.str
    'Largest key in the file (human-readable string representation).'

    def __init__(self, *, epoch: builtins.int=..., id: builtins.int=..., size_bytes: builtins.int=..., smallest_key_info: builtins.str=..., largest_key_info: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['epoch', b'epoch', 'id', b'id', 'largest_key_info', b'largest_key_info', 'size_bytes', b'size_bytes', 'smallest_key_info', b'smallest_key_info']) -> None:
        ...
Global___LsmFile: typing_extensions.TypeAlias = LsmFile