from typing import Any, Mapping

def always(condition: bool, message: str, details: Mapping[str, Any]) -> None: ...
def always_or_unreachable(
    condition: bool, message: str, details: Mapping[str, Any]
) -> None: ...
def sometimes(condition: bool, message: str, details: Mapping[str, Any]) -> None: ...
def reachable(message: str, details: Mapping[str, Any]) -> None: ...
def unreachable(message: str, details: Mapping[str, Any]) -> None: ...
