"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from ...... import proto
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetBrokerRequest(google.protobuf.message.Message):
    """GetBrokerRequest returns information about a single broker in the cluster"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NODE_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    'The node ID for the broker. If set to -1, the broker handling the RPC\n    request returns information about itself.\n    '

    def __init__(self, *, node_id: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['node_id', b'node_id']) -> None:
        ...
global___GetBrokerRequest = GetBrokerRequest

@typing.final
class GetBrokerResponse(google.protobuf.message.Message):
    """GetBrokerResponse is the response from the GetBroker RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BROKER_FIELD_NUMBER: builtins.int

    @property
    def broker(self) -> global___Broker:
        """The specified broker and it's information."""

    def __init__(self, *, broker: global___Broker | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['broker', b'broker']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['broker', b'broker']) -> None:
        ...
global___GetBrokerResponse = GetBrokerResponse

@typing.final
class ListBrokersRequest(google.protobuf.message.Message):
    """ListBrokersRequest returns information about all the brokers in the cluster"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___ListBrokersRequest = ListBrokersRequest

@typing.final
class ListBrokersResponse(google.protobuf.message.Message):
    """ListBrokersResponse is the response from the ListBrokers RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BROKERS_FIELD_NUMBER: builtins.int

    @property
    def brokers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Broker]:
        """The brokers in the cluster and their information."""

    def __init__(self, *, brokers: collections.abc.Iterable[global___Broker] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['brokers', b'brokers']) -> None:
        ...
global___ListBrokersResponse = ListBrokersResponse

@typing.final
class ListKafkaConnectionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NODE_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    'The node ID for the broker. If set to -1, the broker handling the RPC\n    request returns information about itself.\n    '
    page_size: builtins.int
    'The maximum number of connections to return. If unspecified or 0, a\n    default value may be applied. Note that paging is currently not fully\n    supported, and this field only acts as a limit for the first page of data\n    returned. Subsequent pages of data cannot be requested.\n    '
    filter: builtins.str
    'Filter expression to apply to the connection list.\n    Uses a subset of AIP-160 filter syntax supporting:\n    - Field comparisons (`=`, `!=`, `<`, `>`, `<=`, `>=`)\n    - Logical AND chaining: condition1 AND condition2\n    - Nested field access: parent.child = value\n    - Escape sequences: field = "string with \\"quotes\\""\n    - Enum types\n    - RFC3339 timestamps and ISO-like duration\n\n    Limitations (not supported):\n    - Logical OR chaining\n    - Parentheses `(` `)` for grouping\n    - Map and repeated types\n    - HAS (:) operator\n    - Negation (-, NOT)\n    - Bare literal matching\n\n    Example filters:\n    - `state = KAFKA_CONNECTION_STATE_OPEN`\n    - `idle_duration > 30s AND request_count_total > 100`\n    - `authentication_info.user_principal = "my-producer"`\n    - `recent_request_statistics.produce_bytes > 1000 AND\n    client_software_name = "kgo"`\n    - `open_time >= 2025-09-01T10:22:54Z`\n\n    Reference: https://google.aip.dev/160\n    '
    order_by: builtins.str
    'Field-based ordering specification following AIP-132 syntax.\n    Supports multiple fields with `asc`/`desc` direction indicators.\n    Examples:\n    - `idle_duration desc` - longest idle connections first\n    - `open_time desc, total_request_statistics.request_count desc` - newest\n    connections first, then most active\n    - `recent_request_statistics.produce_bytes desc` - connections with\n    highest current produce throughput first\n\n    Reference: https://google.aip.dev/132#ordering\n    '

    def __init__(self, *, node_id: builtins.int=..., page_size: builtins.int=..., filter: builtins.str=..., order_by: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['filter', b'filter', 'node_id', b'node_id', 'order_by', b'order_by', 'page_size', b'page_size']) -> None:
        ...
global___ListKafkaConnectionsRequest = ListKafkaConnectionsRequest

@typing.final
class ListKafkaConnectionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONNECTIONS_FIELD_NUMBER: builtins.int
    TOTAL_SIZE_FIELD_NUMBER: builtins.int
    total_size: builtins.int
    'Total number of connections matching the request.\n    This may be greater than `len(connections)` if some connections were\n    omitted from the response due to the specified (or default) `page_size`.\n    Example:\n      request.page_size = 10\n      response.connections = [<10 items>]\n      response.total_size = 13\n    '

    @property
    def connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.redpanda.core.admin.v2.kafka_connections_pb2.KafkaConnection]:
        """The list of connections matching the request.
        Note that in addition to open connections, some recently-closed
        connections may also be included here. If you don't want to include
        closed connections, set the filter in the request to `state =
        KAFKA_CONNECTION_STATE_OPEN`.
        """

    def __init__(self, *, connections: collections.abc.Iterable[proto.redpanda.core.admin.v2.kafka_connections_pb2.KafkaConnection] | None=..., total_size: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['connections', b'connections', 'total_size', b'total_size']) -> None:
        ...
global___ListKafkaConnectionsResponse = ListKafkaConnectionsResponse

@typing.final
class Broker(google.protobuf.message.Message):
    """The resource for an individual broker within the Kafka Cluster."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NODE_ID_FIELD_NUMBER: builtins.int
    BUILD_INFO_FIELD_NUMBER: builtins.int
    ADMIN_SERVER_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    "This broker's node ID."

    @property
    def build_info(self) -> global___BuildInfo:
        """The build this broker is running."""

    @property
    def admin_server(self) -> global___AdminServer:
        """The admin server information."""

    def __init__(self, *, node_id: builtins.int=..., build_info: global___BuildInfo | None=..., admin_server: global___AdminServer | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['admin_server', b'admin_server', 'build_info', b'build_info']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['admin_server', b'admin_server', 'build_info', b'build_info', 'node_id', b'node_id']) -> None:
        ...
global___Broker = Broker

@typing.final
class BuildInfo(google.protobuf.message.Message):
    """BuildInfo contains information about the Redpanda build."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    BUILD_SHA_FIELD_NUMBER: builtins.int
    version: builtins.str
    'A version string of Redpanda like "v25.2.1" '
    build_sha: builtins.str
    'The git commit SHA of the build.'

    def __init__(self, *, version: builtins.str=..., build_sha: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['build_sha', b'build_sha', 'version', b'version']) -> None:
        ...
global___BuildInfo = BuildInfo

@typing.final
class AdminServer(google.protobuf.message.Message):
    """AdminServer has information about the admin server within the broker."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ROUTES_FIELD_NUMBER: builtins.int

    @property
    def routes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RPCRoute]:
        """All of the ConnectRPC routes available on this admin server."""

    def __init__(self, *, routes: collections.abc.Iterable[global___RPCRoute] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['routes', b'routes']) -> None:
        ...
global___AdminServer = AdminServer

@typing.final
class RPCRoute(google.protobuf.message.Message):
    """A route in the Admin API RPC server."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    HTTP_ROUTE_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the RPC method.\n\n    For example `redpanda.core.admin.v2.AdminService.GetVersion`\n    '
    http_route: builtins.str
    'The HTTP route for this RPC method.\n\n    For example `/redpanda.core.admin.v2.AdminService/GetVersion`\n    '

    def __init__(self, *, name: builtins.str=..., http_route: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['http_route', b'http_route', 'name', b'name']) -> None:
        ...
global___RPCRoute = RPCRoute