"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FinalizeUpgradeRequest(google.protobuf.message.Message):
    """FinalizeUpgradeRequest takes no parameters: the target version is
    determined from current cluster state.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___FinalizeUpgradeRequest: typing_extensions.TypeAlias = FinalizeUpgradeRequest

@typing.final
class FinalizeUpgradeResponse(google.protobuf.message.Message):
    """FinalizeUpgradeResponse is returned on successful submission. The
    actual version advance happens asynchronously on the controller
    leader's background loop; poll the cluster's active version (via
    `GET /v1/features`) to confirm.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___FinalizeUpgradeResponse: typing_extensions.TypeAlias = FinalizeUpgradeResponse