"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _IcebergLifecycleState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IcebergLifecycleStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IcebergLifecycleState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ICEBERG_LIFECYCLE_STATE_UNSPECIFIED: _IcebergLifecycleState.ValueType
    ICEBERG_LIFECYCLE_STATE_LIVE: _IcebergLifecycleState.ValueType
    ICEBERG_LIFECYCLE_STATE_CLOSED: _IcebergLifecycleState.ValueType
    ICEBERG_LIFECYCLE_STATE_PURGED: _IcebergLifecycleState.ValueType

class IcebergLifecycleState(_IcebergLifecycleState, metaclass=_IcebergLifecycleStateEnumTypeWrapper):
    """IcebergLifecycleState mirrors the coordinator's per-topic lifecycle. Named
    distinctly from the internal DatalakeService's LifecycleState because both
    generate into the proto::admin C++ namespace.
    """
ICEBERG_LIFECYCLE_STATE_UNSPECIFIED: IcebergLifecycleState.ValueType
ICEBERG_LIFECYCLE_STATE_LIVE: IcebergLifecycleState.ValueType
ICEBERG_LIFECYCLE_STATE_CLOSED: IcebergLifecycleState.ValueType
ICEBERG_LIFECYCLE_STATE_PURGED: IcebergLifecycleState.ValueType
Global___IcebergLifecycleState: typing_extensions.TypeAlias = IcebergLifecycleState

@typing.final
class GetIcebergStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOPICS_FILTER_FIELD_NUMBER: builtins.int

    @property
    def topics_filter(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of Iceberg topics to report on. If empty, returns all Iceberg
        topics known to the coordinator.
        """

    def __init__(self, *, topics_filter: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['topics_filter', b'topics_filter']) -> None:
        ...
Global___GetIcebergStatusRequest: typing_extensions.TypeAlias = GetIcebergStatusRequest

@typing.final
class GetIcebergStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CATALOG_FIELD_NUMBER: builtins.int
    TOPICS_FIELD_NUMBER: builtins.int

    @property
    def catalog(self) -> Global___CatalogHealth:
        ...

    @property
    def topics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TopicIcebergStatus]:
        ...

    def __init__(self, *, catalog: Global___CatalogHealth | None=..., topics: collections.abc.Iterable[Global___TopicIcebergStatus] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['catalog', b'catalog']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['catalog', b'catalog', 'topics', b'topics']) -> None:
        ...
Global___GetIcebergStatusResponse: typing_extensions.TypeAlias = GetIcebergStatusResponse

@typing.final
class CatalogHealth(google.protobuf.message.Message):
    """CatalogHealth reports whether the Iceberg catalog is reachable. On failure,
    error_code is the iceberg::catalog_errc enum name (e.g. "io_error",
    "timedout") and error_message is a human-readable diagnostic.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REACHABLE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    reachable: builtins.bool
    error_code: builtins.str
    error_message: builtins.str

    def __init__(self, *, reachable: builtins.bool=..., error_code: builtins.str=..., error_message: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['error_code', b'error_code', 'error_message', b'error_message', 'reachable', b'reachable']) -> None:
        ...
Global___CatalogHealth: typing_extensions.TypeAlias = CatalogHealth

@typing.final
class TopicIcebergStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOPIC_FIELD_NUMBER: builtins.int
    LIFECYCLE_STATE_FIELD_NUMBER: builtins.int
    PARTITIONS_FIELD_NUMBER: builtins.int
    topic: builtins.str
    lifecycle_state: Global___IcebergLifecycleState.ValueType

    @property
    def partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PartitionIcebergStatus]:
        ...

    def __init__(self, *, topic: builtins.str=..., lifecycle_state: Global___IcebergLifecycleState.ValueType=..., partitions: collections.abc.Iterable[Global___PartitionIcebergStatus] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['lifecycle_state', b'lifecycle_state', 'partitions', b'partitions', 'topic', b'topic']) -> None:
        ...
Global___TopicIcebergStatus: typing_extensions.TypeAlias = TopicIcebergStatus

@typing.final
class PartitionIcebergStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int
    LAST_TRANSLATED_OFFSET_FIELD_NUMBER: builtins.int
    LAST_COMMITTED_OFFSET_FIELD_NUMBER: builtins.int
    COMMIT_LAG_FIELD_NUMBER: builtins.int
    partition: builtins.int
    last_translated_offset: builtins.int
    'Highest Kafka offset written to Parquet (inclusive). Unset if nothing\n    has been translated yet.\n    '
    last_committed_offset: builtins.int
    'Last Kafka offset committed to the Iceberg catalog. Unset if nothing has\n    been committed yet.\n    '
    commit_lag: builtins.int
    'Number of records written to Parquet but not yet committed to the\n    catalog.\n    '

    def __init__(self, *, partition: builtins.int=..., last_translated_offset: builtins.int | None=..., last_committed_offset: builtins.int | None=..., commit_lag: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_last_committed_offset', b'_last_committed_offset', '_last_translated_offset', b'_last_translated_offset', 'last_committed_offset', b'last_committed_offset', 'last_translated_offset', b'last_translated_offset']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_last_committed_offset', b'_last_committed_offset', '_last_translated_offset', b'_last_translated_offset', 'commit_lag', b'commit_lag', 'last_committed_offset', b'last_committed_offset', 'last_translated_offset', b'last_translated_offset', 'partition', b'partition']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_last_committed_offset', b'_last_committed_offset']) -> typing.Literal['last_committed_offset'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_last_translated_offset', b'_last_translated_offset']) -> typing.Literal['last_translated_offset'] | None:
        ...
Global___PartitionIcebergStatus: typing_extensions.TypeAlias = PartitionIcebergStatus