"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ResolveOidcIdentityRequest(google.protobuf.message.Message):
    """=============================================

    ResolveOidcIdentityRequest is the request for the ResolveOidcIdentity RPC.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ResolveOidcIdentityRequest: typing_extensions.TypeAlias = ResolveOidcIdentityRequest

@typing.final
class ResolveOidcIdentityResponse(google.protobuf.message.Message):
    """ResolveOidcIdentityResponse is the response from the ResolveOidcIdentity RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRINCIPAL_FIELD_NUMBER: builtins.int
    EXPIRE_FIELD_NUMBER: builtins.int
    principal: builtins.str
    'The principal resolved from the OIDC token.'

    @property
    def expire(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The timestamp of the token's expiry."""

    def __init__(self, *, principal: builtins.str=..., expire: google.protobuf.timestamp_pb2.Timestamp | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['expire', b'expire']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['expire', b'expire', 'principal', b'principal']) -> None:
        ...
Global___ResolveOidcIdentityResponse: typing_extensions.TypeAlias = ResolveOidcIdentityResponse

@typing.final
class RefreshOidcKeysRequest(google.protobuf.message.Message):
    """RefreshOidcKeysRequest is the request for the RefreshOidcKeys RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___RefreshOidcKeysRequest: typing_extensions.TypeAlias = RefreshOidcKeysRequest

@typing.final
class RefreshOidcKeysResponse(google.protobuf.message.Message):
    """RefreshOidcKeysResponse is the response from the RefreshOidcKeys RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___RefreshOidcKeysResponse: typing_extensions.TypeAlias = RefreshOidcKeysResponse

@typing.final
class RevokeOidcSessionsRequest(google.protobuf.message.Message):
    """RevokeOidcSessionsRequest is the request for the RevokeOidcSessions RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___RevokeOidcSessionsRequest: typing_extensions.TypeAlias = RevokeOidcSessionsRequest

@typing.final
class RevokeOidcSessionsResponse(google.protobuf.message.Message):
    """RevokeOidcSessionsResponse is the response from the RevokeOidcSessions RPC."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___RevokeOidcSessionsResponse: typing_extensions.TypeAlias = RevokeOidcSessionsResponse