apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
  - localhost/redpanda-operator:dev
testDirs:
  - ./tests/e2e-v2
kindConfig: ./kind.yaml
kindNodeCache: false
commands:
  - command: mkdir -p tests/_e2e_artifacts_v2
  - command: kubectl taint nodes -l node-role.kubernetes.io/master= node-role.kubernetes.io/master:NoSchedule-
    ignoreFailure: true
  - command: ./hack/install-cert-manager.sh tests/_e2e_artifacts_v2
  - command: bash -c "kubectl kustomize https://github.com/redpanda-data/redpanda//src/go/k8s/config/crd | kubectl apply -f -"
  - command: helm dep up helm-chart/charts/redpanda-operator/
  - command: helm install --set scope=Namespace --set logLevel=trace --set image.tag=dev
      --set image.repository=localhost/redpanda-operator --namespace redpanda --create-namespace
      redpanda-operator ./helm-chart/charts/redpanda-operator
artifactsDir: tests/_e2e_artifacts_v2
timeout: 360
reportFormat: xml
parallel: 4
namespace: redpanda
suppress:
  - events
