from _typeshed import Incomplete
from collections.abc import Generator
from ducktape.errors import DucktapeError as DucktapeError
from ducktape.utils.http_utils import HttpMixin as HttpMixin
from ducktape.utils.util import wait_until as wait_until
from paramiko import MissingHostKeyPolicy

def check_ssh(method): ...

class RemoteAccountSSHConfig:
    host: Incomplete
    hostname: Incomplete
    user: Incomplete
    port: Incomplete
    password: Incomplete
    identityfile: Incomplete
    def __init__(self, host: Incomplete | None = ..., hostname: Incomplete | None = ..., user: Incomplete | None = ..., port: Incomplete | None = ..., password: Incomplete | None = ..., identityfile: Incomplete | None = ..., **kwargs) -> None: ...
    @staticmethod
    def from_string(config_str): ...
    def to_json(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class RemoteAccountError(DucktapeError):
    account_str: Incomplete
    msg: Incomplete
    def __init__(self, account, msg) -> None: ...

class RemoteCommandError(RemoteAccountError):
    account_str: Incomplete
    exit_status: Incomplete
    cmd: Incomplete
    msg: Incomplete
    def __init__(self, account, cmd, exit_status, msg) -> None: ...

class RemoteAccount(HttpMixin):
    ssh_config: Incomplete
    hostname: Incomplete
    ssh_hostname: Incomplete
    user: Incomplete
    externally_routable_ip: Incomplete
    os: Incomplete
    def __init__(self, ssh_config, externally_routable_ip: Incomplete | None = ..., logger: Incomplete | None = ..., ssh_exception_checks=...) -> None: ...
    @property
    def operating_system(self): ...
    @property
    def logger(self): ...
    @logger.setter
    def logger(self, logger) -> None: ...
    @property
    def ssh_client(self): ...
    @property
    def sftp_client(self): ...
    def close(self) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def wait_for_http_service(self, port, headers, timeout: int = ..., path: str = ...): ...
    def ssh(self, cmd, allow_fail: bool = ...): ...
    def ssh_capture(self, cmd, allow_fail: bool = ..., callback: Incomplete | None = ..., combine_stderr: bool = ..., timeout_sec: Incomplete | None = ...): ...
    def ssh_output(self, cmd, allow_fail: bool = ..., combine_stderr: bool = ..., timeout_sec: Incomplete | None = ...): ...
    def alive(self, pid): ...
    def signal(self, pid, sig, allow_fail: bool = ...) -> None: ...
    def kill_process(self, process_grep_str, clean_shutdown: bool = ..., allow_fail: bool = ...) -> None: ...
    def java_pids(self, match): ...
    def kill_java_processes(self, match, clean_shutdown: bool = ..., allow_fail: bool = ...) -> None: ...
    def copy_between(self, src, dest, dest_node) -> None: ...
    def scp_from(self, src, dest, recursive: bool = ...) -> None: ...
    def copy_from(self, src, dest) -> None: ...
    def scp_to(self, src, dest, recursive: bool = ...) -> None: ...
    def copy_to(self, src, dest) -> None: ...
    def islink(self, path): ...
    def isdir(self, path): ...
    def exists(self, path): ...
    def isfile(self, path): ...
    def open(self, path, mode: str = ...): ...
    def create_file(self, path, contents) -> None: ...
    def mkdir(self, path, mode=...) -> None: ...
    def mkdirs(self, path, mode=...) -> None: ...
    def remove(self, path, allow_fail: bool = ...) -> None: ...
    def monitor_log(self, log) -> Generator[Incomplete, None, None]: ...

class SSHOutputIter:
    iter_obj_func: Incomplete
    iter_obj: Incomplete
    channel_file: Incomplete
    sentinel: Incomplete
    cached: Incomplete
    def __init__(self, iter_obj_func, channel_file: Incomplete | None = ...) -> None: ...
    def __iter__(self): ...
    def next(self): ...
    __next__ = next
    def has_next(self, timeout_sec: Incomplete | None = ...): ...

class LogMonitor:
    acct: Incomplete
    log: Incomplete
    offset: Incomplete
    def __init__(self, acct, log, offset) -> None: ...
    def wait_until(self, pattern, **kwargs): ...

class IgnoreMissingHostKeyPolicy(MissingHostKeyPolicy):
    def missing_host_key(self, client, hostname, key) -> None: ...
