# Invoke the backport bot whenever we merge into dev.

name: backport-on-merge

on:
  push:
    branches:
      - dev

env:
  SCRIPT_DIR: "${{ github.workspace }}/.github/workflows/scripts/backport-command"
  PR_NUMBER: ${{ github.event.number }}

jobs:
  backport-on-merge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: closed
      - run: echo "PR_NUMBER=${PR}" >>"$GITHUB_ENV"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Backport On Merge
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
        id: extract_required_backports_from_pr_body
        run: $SCRIPT_DIR/backport_on_merge.sh
        shell: bash
