name: Lint includes

on:
  push:
    branches:
      - dev
  pull_request:
    paths:
      - 'src/v/**'
      - '.github/workflows/lint-includes.yml'

jobs:
  py:
    name: Lint includes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run includes check
      run: python tools/lint-includes src/v
