# Copyright 2020 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: Lint all codez
on:
  push:
    tags: 'v2**'
    branches:
      - dev
      - release
  pull_request:
    branches:
      - main
      - dev

jobs:
  go:
    name: Lint go files
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8
      id: go

    - name: install gofumpt
      working-directory: src/go/rpk
      run: |
        go install mvdan.cc/gofumpt@v0.3.0

    - name: format go files
      working-directory: src/go
      run: |
        find . -name *.go -type f | xargs -n1 gofumpt -w -lang=1.17
        git diff --exit-code

    - name: lint rpk
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45.2
        working-directory: src/go/rpk/

  js:
    name: Lint js files
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.16.1'

    - name: Set up prettier
      run: npm install prettier@2.3.0

    - name: Lint JS files
      run: npx prettier --list-different src/**/*.{ts,js}

  py:
    name: Lint python files
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up python
      run: |
        sudo apt-get install -y python3 python3-pip
        sudo pip install yapf==0.30.0

    - name: lint python files
      run: find . -name *.py -type f | xargs -n1 yapf -d

  cpp:
    name: Lint files with clang-format
    runs-on: ubuntu-20.04
    steps:

    - name: Fetch clang-format
      run: |
        curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository --yes --update 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main'
        sudo apt-get install -y git clang-format-14
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run clang fmt
      run: |
        find . -regex '.*\.\(cpp\|h\|hpp\|cc\|proto\|java\)' | xargs -n1 clang-format-14 -i -style=file -fallback-style=none
        git diff --exit-code

  sh:
    name: Lint shell scripts
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: setup shfmt
      run: |
        wget "https://github.com/mvdan/sh/releases/download/v3.2.0/shfmt_v3.2.0_linux_amd64" -O shfmt
        chmod +x shfmt

    - name: Run shfmt
      run: ./shfmt -i 2 -ci -s -d .
