name: old-backports
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  alert-on-abandoned-backports:
    outputs:
      OUTPUT: ${{ steps.get-output.outputs.OUTPUT }}
    runs-on: ubuntu-latest

    steps:
    - name: Get output
      id: get-output
      run: |
        echo OUTPUT=$(gh search issues --label "kind/backport" --state open --repo "redpanda-data/redpanda" --updated "<`date --date="15 days ago" +"%Y"-"%m"-"%d"`" --sort updated --order asc --limit 15 --json "assignees,updatedAt,url" --jq '.[] | "@" + (.assignees[] | {login} | .login), .url, .updatedAt,"----"') >>"$GITHUB_OUTPUT"
      shell: bash

    - name: "Post to a test channel (temporary)"
      id: send-slack-message
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "C05DHDW4VCL"
        slack-message: "Test: ${{ steps.get-output.outputs.OUTPUT }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.VBOTBUILDOVICH_SLACK_BOT_TOKEN }}
