name: promote
on:
  release:
    types: [published]

jobs:
  trigger-promote:
    runs-on: ubuntu-latest
    steps:
      - name: trigger k8s pipeline
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.BUILDKITE_TOKEN }}
          pipeline: "redpanda/redpanda"
          branch: "${{.github.ref_name}}"
          build_env_vars: '{"PROMOTE_REDPANDA_FROM_STAGING": "1", "TARGET_VERSION": "${{ github.ref_name }}"}'
