# Copyright 2023 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: transform-sdk-release
on:
  push:
    tags:
      - 'transform-sdk/*'

jobs:
  list-golang:
    name: List Golang Transform SDK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Create golang specific tag
        id: gotag
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{github.ref_name}}'.slice('transform-sdk/'.length);
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/src/transform-sdk/go/transform/' + version,
              sha: context.sha
            });
            // Return the result so we can use it to publish via `go list` below.
            return version;
          result-encoding: string
      - name: List module
        working-directory: src/transform-sdk/go
        # https://go.dev/doc/modules/publishing
        run: 
          go list -m github.com/redpanda-data/redpanda/src/transform-sdk/go/transform@${{steps.gotag.outputs.result}}

  publish-rust:
    name: Publish Rust Transform SDK
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable --no-self-update && rustup default stable

      - name: Publish
        working-directory: src/transform-sdk/rust
        run: |
          pip install tomlkit
          ./scripts/publish.py --version ${{github.ref_name}}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
